### Add new post

POST http://localhost:3000/post
Content-Type: application/json

{
    "username": "A test for comments",
    "description": "TESTI",
    "phone_number": "TASTY"
}

### Get all posts

GET http://localhost:3000/post


### Get post by id

GET http://localhost:3000/post/6738ea676add071cbac046f4
 

### Get post by username

GET http://localhost:3000/post?username=ori
  

### Update post by id

PUT http://localhost:3000/post/6738ea676add071cbac046f4
Content-Type: application/json

{
    "username": "shahar",
    "description": "blabla",
    "phone_number": "1234567890"
}

### Delete post by id

DELETE http://localhost:3000/post/6738e766fcef3656448ff21f



### ALL COMMENTS REQUESTS



### Create a comment
POST http://localhost:3000/post/6739cc076163010dc09bc37e/comments
Content-Type: application/json

{
    "username": "Fifth",
    "description": "Comment"
}

### Get all comments in a post

GET http://localhost:3000/post/6739cc076163010dc09bc37e/comments


### get a comment in a post by ID

GET http://localhost:3000/post/6739cc076163010dc09bc37e/comments/6739cc1a6163010dc09bc381

### Update a comment in a post by ID

PUT http://localhost:3000/post/6739c394ba664a9e6b0fec2f/comments/6739c68b101e01a2387149d4
Content-Type: application/json

{
    "username": "ori",
    "description": "test test"
}

### Delete a comment in a post by ID

DELETE http://localhost:3000/post/6739cc076163010dc09bc37e/comments/6739cc1a6163010dc09bc381

