### Add new post

POST http://localhost:3000/post
Content-Type: application/json

{
    "username": "Check Get Post By ID",
    "description": "Content 1",
    "phone_number": "1234567890"
}

### Get all posts

GET http://localhost:3000/post


###

GET http://localhost:3000/post/6739a988476389c2b663889a 
 

