### POSTS API

### CRAETE POST

POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "Ori",
    "description": "ThisIsPost1",
    "phoneNumber": "1234567890"
}

### GET POSTS

GET http://localhost:3000/post


### GET POST BY ID

GET http://localhost:3000/post/6769cf3c875f57d9a4771791


### GET POST BY SENDER

GET http://localhost:3000/post?sender=Ori


### UPDATE POST

PUT http://localhost:3000/post/6769cf3c875f57d9a4771791
Content-Type: application/json

{
    "description": "Ani"
}

### DELETE POST

DELETE http://localhost:3000/post/6769d3b6aaff55d685139fe5

### COMMENTS API

### CREATE COMMENT

POST http://localhost:3000/comment
Content-Type: application/json

{
    "sender": "Ori",
    "description": "ThisIsPost1",
    "PostId": "6769d3b6aaff55d685139fe5"
}

### GET ALL COMMENTS

GET http://localhost:3000/comment


### GET COMMENT BY ID

GET http://localhost:3000/comment/6769d0ca875f57d9a47717a8


### GET COMMENT BY SENDER

GET http://localhost:3000/comment?sender=Ori


### GET COMMENT BY POST ID

GET http://localhost:3000/comment?PostId=6769cbf69d6ec5a0873c7e22


### UPDATE COMMENT

PUT http://localhost:3000/comment/6769d0ca875f57d9a47717a8
Content-Type: application/json

{
    "description": "Ani"
}

### DELETE COMMENT

DELETE http://localhost:3000/comment/6769d3beaaff55d685139fe7





